### ISSUE TITLE
I do not have edit access to this repo

### ISSUE THREAD

**Issue by mitchcieminski** [olin/olinomic#4]
This seems like a problem. Who _does_ have access? Can I _get_ access?

**Comment by mitchcieminski** [comment]
To be clear: I'm the Gamemaster of the game and should be the one with say on edits.

**Comment by jkunimune** [comment]
Hm. It appears I do.

**Comment by mitchcieminski** [comment]
Thanks to @newsch I am now administrator of the repo again. Woohoo!
